version: '3'

services:

  orderer.networkiot.com:
    container_name: orderer.networkiot.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/networkiot.com/orderers/orderer.networkiot.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/networkiot.com/orderers/orderer.networkiot.com/tls/:/var/hyperledger/orderer/tls
        - orderer.networkiot.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.device.networkiot.com:
    container_name: peer0.device.networkiot.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.device.networkiot.com
      - CORE_PEER_ADDRESS=peer0.device.networkiot.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.device.networkiot.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_LOCALMSPID=DeviceMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/device.networkiot.com/peers/peer0.device.networkiot.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/device.networkiot.com/peers/peer0.device.networkiot.com/tls:/etc/hyperledger/fabric/tls
        - peer0.device.networkiot.com:/var/hyperledger/production
    ports:
      - 7051:7051

  peer0.handler.networkiot.com:
    container_name: peer0.handler.networkiot.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.handler.networkiot.com
      - CORE_PEER_ADDRESS=peer0.handler.networkiot.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer0.handler.networkiot.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_LOCALMSPID=HandlerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/handler.networkiot.com/peers/peer0.handler.networkiot.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/handler.networkiot.com/peers/peer0.handler.networkiot.com/tls:/etc/hyperledger/fabric/tls
        - peer0.handler.networkiot.com:/var/hyperledger/production
    ports:
      - 8051:8051

  peer0.region.networkiot.com:
    container_name: peer0.region.networkiot.com
    extends:
        file: peer-base.yaml
        service: peer-base
    environment:
        - CORE_PEER_ID=peer0.region.networkiot.com
        - CORE_PEER_ADDRESS=peer0.region.networkiot.com:9051
        - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
        - CORE_PEER_CHAINCODEADDRESS=peer0.region.networkiot.com:9052
        - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
        - CORE_PEER_LOCALMSPID=RegionMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/region.networkiot.come/peers/peer0.region.networkiot.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/region.networkiot.come/peers/peer0.region.networkiot.com/tls:/etc/hyperledger/fabric/tls
        - peer0.region.networkiot.com:/var/hyperledger/production
    ports:
        - 9051:9051