---
Organizations:

    - &OrdererOrg
        Name: OrdererOrg
        ID: OrdererIOTMSP
        MSPDir: crypto-config/ordererOrganizations/networkiot.com/msp

    - &Device
        Name: DeviceMSP
        ID: DeviceMSP
        MSPDir: crypto-config/peerOrganizations/device.networkiot.com/msp

    - &Handler
        Name: HandlerMSP
        ID: HandlerMSP
        MSPDir: crypto-config/peerOrganizations/handler.networkiot.com/msp

    - &Linkage
        Name: LinkageMSP
        ID: LinkageMSP
        MSPDir: crypto-config/peerOrganizations/linkage.networkiot.com/msp

Application: &ApplicationDefaults
    Organizations:

Orderer: &OrdererDefaults
    OrdererType: solo

    Addresses:
        - orderer.networkiot.com:7050

    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    Organizations:

Profiles:

    OrdererGenesis:
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *Device
                    - *Handler
                    - *Linkage
    ChannelAll:
        Consortium: SampleConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Device
                - *Handler
                - *Linkage
    DeviceChannel:
        Consortium: SampleConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Device
                - *Handler
    LinkageChannel:
        Consortium: SampleConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Linkage
                - *Handler