---
Organizations:

    - &OrdererOrg
        Name: OrdererOrg
        ID: OrdererMSP
        MSPDir: crypto-config/ordererOrganizations/networkiot.com/msp

    - &Device
        Name: DeviceMSP
        ID: DeviceMSP
        MSPDir: crypto-config/peerOrganizations/device.networkiot.com/msp

    - &Linkage
        Name: LinkageMSP
        ID: LinkageMSP
        MSPDir: crypto-config/peerOrganizations/linkage.networkiot.com/msp

Capabilities:
    Channel: &ChannelCapabilities
        V1_4_3: true

    Orderer: &OrdererCapabilities
        V1_4_2: true

    Application: &ApplicationCapabilities
        V1_4_2: true

Application: &ApplicationDefaults
    Organizations:

Orderer: &OrdererDefaults
    OrdererType: solo

    Addresses:
        - orderer.networkiot.com:7050

    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    Organizations:

Channel: &ChannelDefaults

    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"

        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"

        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

    Capabilities:
        <<: *ChannelCapabilities

Profiles:

    OrdererGenesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *Device
                    - *Linkage

    ChannelAll:
        Consortium: SampleConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Device
                - *Linkage
            Capabilities:
                <<: *ApplicationCapabilities