---
Organizations:

    - &OrdererOrg
        Name: OrdererIOT
        ID: OrdererIOTMSP
        MSPDir: crypto-config/ordererOrganizations/networkiot.com/msp

    - &Sensor
        Name: SensorMSP
        ID: SensorMSP
        MSPDir: crypto-config/peerOrganizations/sensor.networkiot.com/msp
        AnchorPeers:
            - Host: peer0.sensor.networkiot.com
              Port: 7051

    - &Handler
        Name: HandlerMSP
        ID: HandlerMSP
        MSPDir: crypto-config/peerOrganizations/handler.networkiot.com/msp
        AnchorPeers:
            - Host: peer0.handler.networkiot.com
              Port: 8051

    - &Linkage
        Name: LinkageMSP
        ID: LinkageMSP
        MSPDir: crypto-config/peerOrganizations/linkage.networkiot.com/msp
        AnchorPeers:
            - Host: peer0.linkage.networkiot.com
              Port: 9051

Application: &ApplicationDefaults
    Organizations:

Orderer: &OrdererDefaults
    OrdererType: solo

    Addresses:
        - orderer.networkiot.com:7050

    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    Organizations:

Profiles:

    OrdererGenesis:
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *Sensor
                    - *Handler
                    - *Linkage
    SensorChannel:
        Consortium: SampleConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Sensor
                - *Handler
    LinkageChannel:
        Consortium: SampleConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Linkage
                - *Handler