# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definición de las organizaciones que gestionan los nodos orderer
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # OrdererIOT
  # ---------------------------------------------------------------------------
  - Name: OrdererIOT
    Domain: networkiot.com
    Specs:
      - Hostname: orderer

# ---------------------------------------------------------------------------
# "PeerOrgs" - Definición de organizaciones que gestionan nodos de peer
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # Sensor organization
  # ---------------------------------------------------------------------------
  - Name: Sensor
    Domain: sensor.networkiot.com
    Template:
      Count: 1
    Users:
      Count: 1
  # ---------------------------------------------------------------------------
  # Handler organization
  # ---------------------------------------------------------------------------
  - Name: Handler
    Domain: handler.networkiot.com
    Template:
      Count: 1
    Users:
      Count: 1
  # ---------------------------------------------------------------------------
  # Linkage organization
  # ---------------------------------------------------------------------------
  - Name: Linkage
    Domain: linkage.networkiot.com
    Template:
      Count: 1
    Users:
      Count: 1
