version: '2'

volumes:
    orderer.networkiot.com:
    peer0.device.networkiot.com:
    peer0.handler.networkiot.com:
    peer0.linkage.networkiot.com:

networks:
    networkiot:

services:
    orderer.networkiot.com:
        image: hyperledger/fabric-orderer:1.4.4
        environment:
            - FABRIC_LOGGING_SPEC=INFO
            - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
            - ORDERER_GENERAL_GENESISMETHOD=file
            - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
            - ORDERER_GENERAL_LOCALMSPID=OrdererIOTMSP
            - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
            - ORDERER_GENERAL_TLS_ENABLED=false
            - CORE_CHAINCODE_BUILDER=hyperledger/fabric-ccenv:1.4.4
            - CORE_CHAINCODE_GOLANG_RUNTIME=hyperledger/fabric-baseos:amd64-0.4.18
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric
        volumes:
            - ~/tfg/IoTBlockchainAPP/infrastructure/config-network/network/channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
            - ~/tfg/IoTBlockchainAPP/infrastructure/config-network/network/crypto-config/ordererOrganizations/networkiot.com/orderers/orderer.networkiot.com/msp/:/var/hyperledger/orderer/msp/
            - ~/tfg/IoTBlockchainAPP/infrastructure/config-network/network/crypto-config/ordererOrganizations/networkiot.com/orderers/orderer.networkiot.com/tls/:/var/hyperledger/orderer/tls/
        hostname: orderer.networkiot.com
        networks:
            - networkiot    
        ports:
            - 7050:7050
        command: orderer

    peer0.device.networkiot.com:
        image: hyperledger/fabric-peer:1.4.4
        depends_on:
            - orderer.networkiot.com
            - couchdb
        environment: 
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=networkiot
            - FABRIC_LOGGING_SPEC=INFO
            - CORE_PEER_TLS_ENABLED=false
            - CORE_PEER_GOSSIP_USELEADERELECTION=true
            - CORE_PEER_GOSSIP_ORGLEADER=false
            - CORE_PEER_PROFILE_ENABLED=true
            - CORE_PEER_ID=peer0.device.networkiot.com
            - CORE_PEER_ADDRESS=peer0.device.networkiot.com:7051
            - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
            - CORE_PEER_CHAINCODEADDRESS=peer0.device.networkiot.com:7052
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
            - CORE_PEER_LOCALMSPID=DeviceMSP
            - CORE_CHAINCODE_BUILDER=hyperledger/fabric-ccenv:1.4.4
            - CORE_CHAINCODE_GOLANG_RUNTIME=hyperledger/fabric-baseos:amd64-0.4.18
            - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
            - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
            - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
            - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=admin
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        volumes:
            - /var/run/:/host/var/run/
            - ~/tfg/IoTBlockchainAPP/infrastructure/config-network/network/crypto-config/peerOrganizations/device.networkiot.com/peers/peer0.device.networkiot.com/msp/:/etc/hyperledger/fabric/msp/
            - ~/tfg/IoTBlockchainAPP/infrastructure/config-network/network/crypto-config/peerOrganizations/device.networkiot.com/peers/peer0.device.networkiot.com/tls/:/etc/hyperledger/fabric/tls/
            - ~/tfg/IoTBlockchainAPP/infrastructure/config-network/network/crypto-config/peerOrganizations/device.networkiot.com/users/:/etc/hyperledger/fabric/users/
        hostname: peer0.device.networkiot.com
        networks:
            - networkiot
        ports:
            - 7051:7051
        command: peer node start
    
    caDevice:
        image: hyperledger/fabric-ca:1.4.4
        environment:
            - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
            - FABRIC_CA_SERVER_CA_NAME=caDevice
            - FABRIC_CA_SERVER_TLS_ENABLED=false
            - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.device.networkiot.com-cert.pem
            - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/${DEVICE_CA_KEY}
        volumes:
            - ~/tfg/IoTBlockchainAPP/infrastructure/config-network/network/crypto-config/peerOrganizations/device.networkiot.com/ca/:/etc/hyperledger/fabric-ca-server-config
        ports:
            - 7054:7054
        command: sh -c 'fabric-ca-server start -b admin:admin'
        
    peer0.handler.networkiot.com:
        image: hyperledger/fabric-peer:1.4.4
        depends_on:
            - orderer.networkiot.com
            - couchdb
        environment: 
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=networkiot
            - FABRIC_LOGGING_SPEC=INFO
            - CORE_PEER_TLS_ENABLED=false
            - CORE_PEER_GOSSIP_USELEADERELECTION=true
            - CORE_PEER_GOSSIP_ORGLEADER=false
            - CORE_PEER_PROFILE_ENABLED=true
            - CORE_PEER_ID=peer0.handler.networkiot.com
            - CORE_PEER_ADDRESS=peer0.handler.networkiot.com:7051
            - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
            - CORE_PEER_CHAINCODEADDRESS=peer0.handler.networkiot.com:7052
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
            - CORE_PEER_LOCALMSPID=HandlerMSP
            - CORE_CHAINCODE_BUILDER=hyperledger/fabric-ccenv:1.4.4
            - CORE_CHAINCODE_GOLANG_RUNTIME=hyperledger/fabric-baseos:amd64-0.4.18
            - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
            - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
            - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
            - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=admin
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        volumes:
            - /var/run/:/host/var/run/
            - ~/tfg/IoTBlockchainAPP/infrastructure/config-network/network/crypto-config/peerOrganizations/handler.networkiot.com/peers/peer0.handler.networkiot.com/msp/:/etc/hyperledger/fabric/msp/
            - ~/tfg/IoTBlockchainAPP/infrastructure/config-network/network/crypto-config/peerOrganizations/handler.networkiot.com/peers/peer0.handler.networkiot.com/tls/:/etc/hyperledger/fabric/tls/
        hostname: peer0.handler.networkiot.com
        networks:
            - networkiot
        ports:
            - 8051:7051
        command: peer node start

    caHandler:
        image: hyperledger/fabric-ca:1.4.4
        environment:
            - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
            - FABRIC_CA_SERVER_CA_NAME=caHandler
            - FABRIC_CA_SERVER_TLS_ENABLED=false
            - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.handler.networkiot.com-cert.pem
            - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/${HANDLER_CA_KEY}
        volumes:
            - ~/tfg/IoTBlockchainAPP/infrastructure/config-network/network/crypto-config/peerOrganizations/handler.networkiot.com/ca/:/etc/hyperledger/fabric-ca-server-config
        ports:
            - 8054:7054
        command: sh -c 'fabric-ca-server start -b admin:admin'

    peer0.linkage.networkiot.com:
        image: hyperledger/fabric-peer:1.4.4
        depends_on:
            - orderer.networkiot.com
            - couchdb
        environment: 
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=networkiot
            - FABRIC_LOGGING_SPEC=INFO
            - CORE_PEER_TLS_ENABLED=true
            - CORE_PEER_GOSSIP_USELEADERELECTION=true
            - CORE_PEER_GOSSIP_ORGLEADER=false
            - CORE_PEER_PROFILE_ENABLED=true
            - CORE_PEER_ID=peer0.linkage.networkiot.com
            - CORE_PEER_ADDRESS=peer0.linkage.networkiot.com:7051
            - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
            - CORE_PEER_CHAINCODEADDRESS=peer0.linkage.networkiot.com:7052
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
            - CORE_PEER_LOCALMSPID=LinkageMSP
            - CORE_CHAINCODE_BUILDER=hyperledger/fabric-ccenv:1.4.4
            - CORE_CHAINCODE_GOLANG_RUNTIME=hyperledger/fabric-baseos:amd64-0.4.18
            - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
            - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
            - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
            - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=admin
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        volumes:
            - /var/run/:/host/var/run/
            - ~/tfg/IoTBlockchainAPP/infrastructure/config-network/network/crypto-config/peerOrganizations/linkage.networkiot.com/peers/peer0.linkage.networkiot.com/msp/:/etc/hyperledger/fabric/msp/
            - ~/tfg/IoTBlockchainAPP/infrastructure/config-network/network/crypto-config/peerOrganizations/linkage.networkiot.com/peers/peer0.linkage.networkiot.com/tls/:/etc/hyperledger/fabric/tls/
            - ~/tfg/IoTBlockchainAPP/infrastructure/config-network/network/crypto-config/peerOrganizations/linkage.networkiot.com/users/:/etc/hyperledger/fabric/users/
        hostname: peer0.linkage.networkiot.com
        networks:
            - networkiot
        ports:
            - 9051:7051
        command: peer node start

    caLinkage:
        image: hyperledger/fabric-ca:1.4.4
        environment:
            - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
            - FABRIC_CA_SERVER_CA_NAME=caLinkage
            - FABRIC_CA_SERVER_TLS_ENABLED=false
            - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.linkage.networkiot.com-cert.pem
            - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/${LINKAGE_CA_KEY}
        volumes:
            - ~/tfg/IoTBlockchainAPP/infrastructure/config-network/network/crypto-config/peerOrganizations/linkage.networkiot.com/ca/:/etc/hyperledger/fabric-ca-server-config
        ports:
            - 9054:7054
        command: sh -c 'fabric-ca-server start -b admin:admin'

    couchdb:
        image: hyperledger/fabric-couchdb:0.4.18
        environment:
            - COUCHDB_USER=admin
            - COUCHDB_PASSWORD=admin
        ports:
            - 5984:5984

    cli:
        image: hyperledger/fabric-tools:1.4.4
        depends_on:
            - orderer.networkiot.com
            - peer0.device.networkiot.com
            - peer0.handler.networkiot.com
            - peer0.linkage.networkiot.com
            - couchdb
        tty: true
        environment:
            - GOPATH=/opt/gopath
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - FABRIC_LOGGING_SPEC=INFO
            - CORE_PEER_ID=cli
            - CORE_PEER_ADDRESS=peer0.handler.networkiot.com:7051
            - CORE_PEER_LOCALMSPID=HandlerMSP
            - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/handler.networkiot.com/users/Admin@handler.networkiot.com/msp
            - CORE_CHAINCODE_BUILDER=hyperledger/fabric-ccenv:1.4.4
            - CORE_CHAINCODE_GOLANG=hyperledger/fabric-baseos:amd64-0.4.18
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        volumes:
            - /var/run/:/host/var/run/
            - ~/tfg/IoTBlockchainAPP/infrastructure/config-network/chaincode/:/opt/gopath/src/github.com/chaincode/
            - ~/tfg/IoTBlockchainAPP/infrastructure/config-network/network/crypto-config/:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
            - ~/tfg/IoTBlockchainAPP/infrastructure/config-network/network/channel-artifacts/:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts/
        networks:
            - networkiot