version: '3'

volumes:
    orderer.networkiot.com:
    peer0.sensor.networkiot.com:
    peer0.handler.networkiot.com:
    peer0.linkage.networkiot.com:

networks:
    networkiot:

services:
    orderer:
        image: thejokeri/fabric-orderer:arm64-1.4.4
        environment:
            - FABRIC_LOGGING_SPEC=INFO
            - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
            - ORDERER_GENERAL_GENESISMETHOD=file
            - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
            - ORDERER_GENERAL_LOCALMSPID=OrdererIOTMSP
            - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
            - ORDERER_GENERAL_TLS_ENABLED=true
            - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
            - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
            - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
            - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
            - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
            - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric
        volumes:
            - ~/IoTBlockchainAPP/infrastructure/config-network/network/channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
            - ~/IoTBlockchainAPP/infrastructure/config-network/network/crypto-config/ordererOrganizations/networkiot.com/orderers/orderer.networkiot.com/msp/:/var/hyperledger/orderer/msp/
            - ~/IoTBlockchainAPP/infrastructure/config-network/network/crypto-config/ordererOrganizations/networkiot.com/orderers/orderer.networkiot.com/tls/:/var/hyperledger/orderer/tls/
            - orderer.networkiot.com:/var/hyperledger/production/orderer
        hostname: orderer.networkiot.com
        networks:
            networkiot:
                aliases:
                    - orderer.networkiot.com
        ports:
            - 7050:7050
        command: orderer

    sensor:
        image: thejokeri/fabric-peer:arm64-1.4.4
        environment: 
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_networkiot
            - FABRIC_LOGGING_SPEC=INFO
            - FABRIC_LOGGING_SPEC=DEBUG
            - CORE_PEER_TLS_ENABLED=true
            - CORE_PEER_GOSSIP_USELEADERELECTION=false
            - CORE_PEER_GOSSIP_ORGLEADER=false
            - CORE_PEER_PROFILE_ENABLED=true
            - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
            - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
            - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
            - CORE_PEER_ID=peer0.sensor.networkiot.com
            - CORE_PEER_ADDRESS=peer0.sensor.networkiot.com:7051
            - CORE_PEER_CHAINCODEADDRESS=peer0.sensor.networkiot.com:7052
            - CORE_PEER_LOCALMSPID=SensorMSP
            - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
            - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
            - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
            - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=admin
        depends_on:
            - orderer
            - couchdb
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        volumes:
            - /var/run/:/host/var/run/
            - ~/IoTBlockchainAPP/infrastructure/config-network/network/crypto-config/peerOrganizations/sensor.networkiot.com/peers/peer0.sensor.networkiot.com/msp/:/etc/hyperledger/fabric/msp/
            - ~/IoTBlockchainAPP/infrastructure/config-network/network/crypto-config/peerOrganizations/sensor.networkiot.com/peers/peer0.sensor.networkiot.com/tls/:/etc/hyperledger/fabric/tls/
            - peer0.sensor.networkiot.com:/var/hyperledger/production
        hostname: peer0.sensor.networkiot.com
        networks:
            networkiot:
                aliases:
                    - peer0.sensor.networkiot.com
        ports:
            - 7051:7051
        command: peer node start

    handler:
        image: thejokeri/fabric-peer:arm64-1.4.4
        environment: 
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_networkiot
            - FABRIC_LOGGING_SPEC=INFO
            - FABRIC_LOGGING_SPEC=DEBUG
            - CORE_PEER_TLS_ENABLED=true
            - CORE_PEER_GOSSIP_USELEADERELECTION=false
            - CORE_PEER_GOSSIP_ORGLEADER=false
            - CORE_PEER_PROFILE_ENABLED=true
            - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
            - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
            - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
            - CORE_PEER_ID=peer0.handler.networkiot.com
            - CORE_PEER_ADDRESS=peer0.handler.networkiot.com:8051
            - CORE_PEER_CHAINCODEADDRESS=peer0.handler.networkiot.com:8052
            - CORE_PEER_LOCALMSPID=HandlerMSP
            - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
            - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
            - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
            - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=admin
        depends_on:
            - orderer
            - couchdb
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        volumes:
            - /var/run/:/host/var/run/
            - ~/IoTBlockchainAPP/infrastructure/config-network/network/crypto-config/peerOrganizations/handler.networkiot.com/peers/peer0.handler.networkiot.com/msp/:/etc/hyperledger/fabric/msp/
            - ~/IoTBlockchainAPP/infrastructure/config-network/network/crypto-config/peerOrganizations/handler.networkiot.com/peers/peer0.handler.networkiot.com/tls/:/etc/hyperledger/fabric/tls/
            - peer0.handler.networkiot.com:/var/hyperledger/production
        hostname: peer0.handler.networkiot.com
        networks:
            networkiot:
                aliases:
                    - peer0.handler.networkiot.com
        ports:
            - 8051:8051
        command: peer node start

    linkage:
        image: thejokeri/fabric-peer:arm64-1.4.4
        environment: 
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_networkiot
            - FABRIC_LOGGING_SPEC=INFO
            - FABRIC_LOGGING_SPEC=DEBUG
            - CORE_PEER_TLS_ENABLED=true
            - CORE_PEER_GOSSIP_USELEADERELECTION=false
            - CORE_PEER_GOSSIP_ORGLEADER=false
            - CORE_PEER_PROFILE_ENABLED=true
            - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
            - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
            - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
            - CORE_PEER_ID=peer0.linkage.networkiot.com
            - CORE_PEER_ADDRESS=peer0.linkage.networkiot.com:9051
            - CORE_PEER_CHAINCODEADDRESS=peer0.linkage.networkiot.com:9052
            - CORE_PEER_LOCALMSPID=LinkageMSP
            - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
            - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
            - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
            - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=admin
        depends_on:
            - orderer
            - couchdb
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        volumes:
            - /var/run/:/host/var/run/
            - ~/IoTBlockchainAPP/infrastructure/config-network/network/crypto-config/peerOrganizations/linkage.networkiot.com/peers/peer0.linkage.networkiot.com/msp/:/etc/hyperledger/fabric/msp/
            - ~/IoTBlockchainAPP/infrastructure/config-network/network/crypto-config/peerOrganizations/linkage.networkiot.com/peers/peer0.linkage.networkiot.com/tls/:/etc/hyperledger/fabric/tls/
            - peer0.linkage.networkiot.com:/var/hyperledger/production
        hostname: peer0.linkage.networkiot.com
        networks:
            networkiot:
                aliases:
                    - peer0.linkage.networkiot.com
        ports:
            - 9051:9051
        command: peer node start

    couchdb:
        container_name: couchdb
        image: thejokeri/fabric-couchdb:arm64-0.4.18
        environment:
            - COUCHDB_USER=admin
            - COUCHDB_PASSWORD=admin
        ports:
            - 5984:5984
        networks:
            networkiot:
                aliases:
                    - couchdb.networkiot.com

    cli:
        image: thejokeri/fabric-tools:arm64-1.4.4
        tty: true
        stdin_open: true
        environment:
            - GOPATH=/opt/gopath
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - FABRIC_LOGGING_SPEC=DEBUG
            - FABRIC_LOGGING_SPEC=INFO
            - CORE_PEER_ID=cli
            - CORE_CHAINCODE_KEEPALIVE=10
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        command: /bin/bash
        volumes:
            - /var/run/:/host/var/run/
            - ~/IoTBlockchainAPP/infrastructure/config-network/chaincode/:/opt/gopath/src/github.com/chaincode/
            - ~/IoTBlockchainAPP/infrastructure/config-network/network/crypto-config/:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
            - ~/IoTBlockchainAPP/infrastructure/config-network/network/channel-artifacts/:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts/
        depends_on:
            - orderer
            - sensor
            - handler
            - linkage
            - couchdb
        networks:
            networkiot:
                aliases:
                    - cli.networkiot.com
