version: '3'

volumes:
  orderer.networkiot.com:
  peer0.device.networkiot.com:
  peer0.handler.networkiot.com:
  peer0.region.networkiot.com:

networks:
  networkiot:

services:

  orderer.networkiot.com:
    container_name: orderer.networkiot.com
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.networkiot.com
    networks:
      - networkiot

  peer0.device.networkiot.com:
    container_name: peer0.device.networkiot.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.device.networkiot.com
    networks:
      - networkiot

  peer0.handler.networkiot.com:
    container_name: peer0.handler.networkiot.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.handler.networkiot.com
    networks:
      - networkiot

  peer0.region.networkiot.com:
    container_name: peer0.region.networkiot.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.region.networkiot.com
    networks:
      - networkiot

  cli:
    container_name: cli
    image: thejokeri/fabric-tools:arm64-1.4.4
    tty: true
    stdin_open: true
    environment:
      - SYS_CHANNEL=$SYS_CHANNEL
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.handler.networkiot.com:8051
      - CORE_PEER_LOCALMSPID=HandlerMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/handler.networkiot.com/peers/peer0.handler.networkiot.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/handler.networkiot.com/peers/peer0.handler.networkiot.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/handler.networkiot.com/peers/peer0.handler.networkiot.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/handler.networkiot.com/users/Admin@handler.networkiot.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.networkiot.com
      - peer0.device.networkiot.com
      - peer0.handler.networkiot.com
      - peer0.region.networkiot.com
    networks:
      - networkiot
