version: '3'

volumes:
    orderer.networkiot.com:
    peer0.device.networkiot.com:
    peer1.device.networkiot.com:
    peer0.linkage.networkiot.com:
    peer1.linkage.networkiot.com:

networks:
    networkiot:
        external: true

services:

    orderer:
        image: thejokeri/fabric-orderer:arm64-1.4.4
        environment:
            - FABRIC_LOGGING_SPEC=INFO
            - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
            - ORDERER_GENERAL_GENESISMETHOD=file
            - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
            - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
            - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
            - ORDERER_GENERAL_TLS_ENABLED=true
            - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
            - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
            - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
            - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
            - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
            - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
            - CORE_CHAINCODE_BUILDER=thejokeri/fabric-ccenv:arm64-1.4.4
            - CORE_CHAINCODE_GOLANG_RUNTIME=thejokeri/fabric-baseos:arm64-0.4.18
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric
        volumes:
            - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
            - ./crypto-config/ordererOrganizations/networkiot.com/orderers/orderer.networkiot.com/msp/:/var/hyperledger/orderer/msp/
            - ./crypto-config/ordererOrganizations/networkiot.com/orderers/orderer.networkiot.com/tls/:/var/hyperledger/orderer/tls/
            - orderer.networkiot.com:/var/hyperledger/production/orderer
        hostname: orderer.networkiot.com
        networks:
            networkiot:
                aliases:
                    - orderer.networkiot.com    
        ports:
            - 7050:7050
        command: orderer
        deploy:
            placement:
                constraints:
                    - "node.role==manager"

    peer0device:
        image: thejokeri/fabric-peer:arm64-1.4.4
        depends_on:
            - orderer
            - couchdbDevice0
        environment: 
            - CORE_PEER_ID=peer0.device.networkiot.com
            - CORE_PEER_ADDRESS=peer0.device.networkiot.com:7051
            - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
            - CORE_PEER_CHAINCODEADDRESS=peer0.device.networkiot.com:7052
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
            - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.device.networkiot.com:8051
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.device.networkiot.com:7051
            - CORE_PEER_LOCALMSPID=DeviceMSP
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=networkiot
            - FABRIC_LOGGING_SPEC=INFO
            - CORE_PEER_TLS_ENABLED=true
            - CORE_PEER_GOSSIP_USELEADERELECTION=true
            - CORE_PEER_GOSSIP_ORGLEADER=false
            - CORE_PEER_PROFILE_ENABLED=true
            - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
            - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
            - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
            - CORE_CHAINCODE_BUILDER=thejokeri/fabric-ccenv:arm64-1.4.4
            - CORE_CHAINCODE_GOLANG_RUNTIME=thejokeri/fabric-baseos:arm64-0.4.18
            - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
            - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdbDevice0:5984
            - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
            - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=admin
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        volumes:
            - /var/run/:/host/var/run/
            - ./crypto-config/peerOrganizations/device.networkiot.com/peers/peer0.device.networkiot.com/msp/:/etc/hyperledger/fabric/msp/
            - ./crypto-config/peerOrganizations/device.networkiot.com/peers/peer0.device.networkiot.com/tls/:/etc/hyperledger/fabric/tls/
            - ./crypto-config/peerOrganizations/device.networkiot.com/users/:/etc/hyperledger/fabric/users/
        hostname: peer0.device.networkiot.com
        networks:
            networkiot:
                aliases:
                    - peer0.device.networkiot.com
        ports:
            - 7051:7051
        command: peer node start
        deploy:
            placement:
                constraints:
                    - "node.role==worker"
  
    couchdbDevice0:
        image: thejokeri/fabric-couchdb:arm64-0.4.18
        environment:
            - COUCHDB_USER=admin
            - COUCHDB_PASSWORD=admin
        ports:
            - 5984:5984
        networks:
            - networkiot
        deploy:
            placement:
                constraints:
                    - "node.role==worker"

    peer1device:
        image: thejokeri/fabric-peer:arm64-1.4.4
        depends_on:
            - orderer
            - couchdbDevice1
        environment: 
            - CORE_PEER_ID=peer1.device.networkiot.com
            - CORE_PEER_ADDRESS=peer1.device.networkiot.com:8051
            - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
            - CORE_PEER_CHAINCODEADDRESS=peer1.device.networkiot.com:8052
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
            - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.device.networkiot.com:7051
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.device.networkiot.com:8051
            - CORE_PEER_LOCALMSPID=DeviceMSP
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=networkiot
            - FABRIC_LOGGING_SPEC=INFO
            - CORE_PEER_TLS_ENABLED=true
            - CORE_PEER_GOSSIP_USELEADERELECTION=true
            - CORE_PEER_GOSSIP_ORGLEADER=false
            - CORE_PEER_PROFILE_ENABLED=true
            - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
            - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
            - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
            - CORE_CHAINCODE_BUILDER=thejokeri/fabric-ccenv:arm64-1.4.4
            - CORE_CHAINCODE_GOLANG_RUNTIME=thejokeri/fabric-baseos:arm64-0.4.18
            - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
            - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdbDevice1:5984
            - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
            - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=admin
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        volumes:
            - /var/run/:/host/var/run/
            - ./crypto-config/peerOrganizations/device.networkiot.com/peers/peer1.device.networkiot.com/msp/:/etc/hyperledger/fabric/msp/
            - ./crypto-config/peerOrganizations/device.networkiot.com/peers/peer1.device.networkiot.com/tls/:/etc/hyperledger/fabric/tls/
            - ./crypto-config/peerOrganizations/device.networkiot.com/users/:/etc/hyperledger/fabric/users/
        hostname: peer1.device.networkiot.com
        networks:
            networkiot:
                aliases:
                    - peer1.device.networkiot.com
        ports:
            - 8051:8051
        command: peer node start
        deploy:
            placement:
                constraints:
                    - "node.role==worker"
    
    couchdbDevice1:
        image: thejokeri/fabric-couchdb:arm64-0.4.18
        environment:
            - COUCHDB_USER=admin
            - COUCHDB_PASSWORD=admin
        ports:
            - 6984:5984
        networks:
            - networkiot
        deploy:
            placement:
                constraints:
                    - "node.role==worker"

    peer0linkage:
        image: thejokeri/fabric-peer:arm64-1.4.4
        depends_on:
            - orderer
            - couchdbLinkage0
        environment: 
            - CORE_PEER_ID=peer0.linkage.networkiot.com
            - CORE_PEER_ADDRESS=peer0.linkage.networkiot.com:9051
            - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
            - CORE_PEER_CHAINCODEADDRESS=peer0.linkage.networkiot.com:9052
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
            - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.linkage.networkiot.com:10051
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.linkage.networkiot.com:9051
            - CORE_PEER_LOCALMSPID=LinkageMSP
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=networkiot
            - FABRIC_LOGGING_SPEC=INFO
            - CORE_PEER_TLS_ENABLED=true
            - CORE_PEER_GOSSIP_USELEADERELECTION=true
            - CORE_PEER_GOSSIP_ORGLEADER=false
            - CORE_PEER_PROFILE_ENABLED=true
            - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
            - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
            - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
            - CORE_CHAINCODE_BUILDER=thejokeri/fabric-ccenv:arm64-1.4.4
            - CORE_CHAINCODE_GOLANG_RUNTIME=thejokeri/fabric-baseos:arm64-0.4.18
            - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
            - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdbLinkage0:5984
            - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
            - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=admin
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        volumes:
            - /var/run/:/host/var/run/
            - ./crypto-config/peerOrganizations/linkage.networkiot.com/peers/peer0.linkage.networkiot.com/msp/:/etc/hyperledger/fabric/msp/
            - ./crypto-config/peerOrganizations/linkage.networkiot.com/peers/peer0.linkage.networkiot.com/tls/:/etc/hyperledger/fabric/tls/
            - ./crypto-config/peerOrganizations/linkage.networkiot.com/users/:/etc/hyperledger/fabric/users/
        hostname: peer0.linkage.networkiot.com
        networks:
            networkiot:
                aliases:
                    - peer0.linkage.networkiot.com
        ports:
            - 9051:9051
        command: peer node start
        deploy:
            placement:
                constraints:
                    - "node.role==worker"
    
    couchdbLinkage0:
        image: thejokeri/fabric-couchdb:arm64-0.4.18
        environment:
            - COUCHDB_USER=admin
            - COUCHDB_PASSWORD=admin
        ports:
            - 7984:5984
        networks:
            networkiot:
                aliases:
                    - networkiot
        deploy:
            placement:
                constraints:
                    - "node.role==worker"

    peer1linkage:
        image: thejokeri/fabric-peer:arm64-1.4.4
        depends_on:
            - orderer
            - couchdbLinkage1
        environment: 
            - CORE_PEER_ID=peer1.linkage.networkiot.com
            - CORE_PEER_ADDRESS=peer1.linkage.networkiot.com:10051
            - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
            - CORE_PEER_CHAINCODEADDRESS=peer1.linkage.networkiot.com:10052
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
            - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.linkage.networkiot.com:9051
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.linkage.networkiot.com:10051
            - CORE_PEER_LOCALMSPID=LinkageMSP
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=networkiot
            - FABRIC_LOGGING_SPEC=INFO
            - CORE_PEER_TLS_ENABLED=true
            - CORE_PEER_GOSSIP_USELEADERELECTION=true
            - CORE_PEER_GOSSIP_ORGLEADER=false
            - CORE_PEER_PROFILE_ENABLED=true
            - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
            - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
            - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
            - CORE_CHAINCODE_BUILDER=thejokeri/fabric-ccenv:arm64-1.4.4
            - CORE_CHAINCODE_GOLANG_RUNTIME=thejokeri/fabric-baseos:arm64-0.4.18
            - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
            - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdbLinkage1:5984
            - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
            - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=admin
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        volumes:
            - /var/run/:/host/var/run/
            - ./crypto-config/peerOrganizations/linkage.networkiot.com/peers/peer1.linkage.networkiot.com/msp/:/etc/hyperledger/fabric/msp/
            - ./crypto-config/peerOrganizations/linkage.networkiot.com/peers/peer1.linkage.networkiot.com/tls/:/etc/hyperledger/fabric/tls/
            - ./crypto-config/peerOrganizations/linkage.networkiot.com/users/:/etc/hyperledger/fabric/users/
        hostname: peer1.linkage.networkiot.com
        networks:
            networkiot:
                aliases:
                    - peer1.linkage.networkiot.com
        ports:
            - 10051:10051
        command: peer node start
        deploy:
            placement:
                constraints:
                    - "node.role==worker"
    
    couchdbLinkage1:
        image: thejokeri/fabric-couchdb:arm64-0.4.18
        environment:
            - COUCHDB_USER=admin
            - COUCHDB_PASSWORD=admin
        ports:
            - 8984:5984
        networks:
            - networkiot
        deploy:
            placement:
                constraints:
                    - "node.role==worker"

    caDevice:
        image: thejokeri/fabric-ca:arm64-1.4.4
        environment:
            - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
            - FABRIC_CA_SERVER_CA_NAME=caDevice
            - FABRIC_CA_SERVER_TLS_ENABLED=true
            - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.device.networkiot.com-cert.pem
            - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/${DEVICE_CA_KEY}
            - FABRIC_CA_SERVER_PORT=7054
        volumes:
            - ./crypto-config/peerOrganizations/device.networkiot.com/ca/:/etc/hyperledger/fabric-ca-server-config
        networks:
            - networkiot
        ports:
            - 7054:7054
        command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.device.networkiot.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/${DEVICE_CA_KEY} -b adminDevice:admin -d'
        deploy:
            placement:
                constraints:
                    - "node.role==worker"

    caLinkage:
        image: thejokeri/fabric-ca:arm64-1.4.4
        environment:
            - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
            - FABRIC_CA_SERVER_CA_NAME=caLinkage
            - FABRIC_CA_SERVER_TLS_ENABLED=true
            - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.linkage.networkiot.com-cert.pem
            - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/${LINKAGE_CA_KEY}
            - FABRIC_CA_SERVER_PORT=8054
        volumes:
            - ./crypto-config/peerOrganizations/linkage.networkiot.com/ca/:/etc/hyperledger/fabric-ca-server-config
        networks:
            - networkiot
        ports:
            - 8054:8054
        command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.linkage.networkiot.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/${LINKAGE_CA_KEY} -b adminLinkage:admin -d'
        deploy:
            placement:
                constraints:
                    - "node.role==worker"

    cli:
        image: thejokeri/fabric-tools:arm64-1.4.4
        depends_on:
            - orderer
            - peer0device
            - peer1device
            - peer0linkage
            - peer1linkage
        tty: true
        stdin_open: true
        environment:
            - SYS_CHANNEL=networkiot
            - GOPATH=/opt/gopath
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - FABRIC_LOGGING_SPEC=INFO
            - CORE_PEER_ID=cli
            - CORE_PEER_ADDRESS=peer0.device.networkiot.com:7051
            - CORE_PEER_LOCALMSPID=DeviceMSP
            - CORE_PEER_TLS_ENABLED=true
            - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/device.networkiot.com/peers/peer0.device.networkiot.com/tls/server.crt
            - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/device.networkiot.com/peers/peer0.device.networkiot.com/tls/server.key
            - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/device.networkiot.com/peers/peer0.device.networkiot.com/tls/ca.crt
            - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/device.networkiot.com/users/Admin@device.networkiot.com/msp
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        command: /bin/bash
        volumes:
            - /var/run/:/host/var/run/
            - ../chaincode/:/opt/gopath/src/github.com/chaincode/
            - ./crypto-config/:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
            - ./channel-artifacts/:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts/
        networks:
            - networkiot
        deploy:
            placement:
                constraints:
                    - "node.role==manager"
